[tool.poetry]
name = "dRFEtools"
packages = [
    {include = "dRFEtools"}
]
version = "0.3.1"
description = "A package for preforming dynamic recursive feature elimination with sklearn."
authors = ["Kynon JM Benjamin <kj.benjamin90@gmail.com>", "Apu√£ Paquola <apua.paquola@libd.org>"]
maintainers = ["Kynon JM Benjamin <kj.benjamin90@gmail.com>"]
license = "GPL-3.0-only"
readme = "README.md"
homepage = "https://github.com/LieberInstitute/dRFEtools.git"
repository = "https://github.com/LieberInstitute/dRFEtools.git"
keywords = ['recursive feature elimination', 'sklearn', 'feature ranking']

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.24.0"
pandas = "^2.0.2"
matplotlib = "^3.7.0"
plotnine = "^0.12.1"
scikit-learn = "^1.2"
scipy = "^1.7"
statsmodels = "^0.14.0"

[tool.poetry.dev-dependencies]
pandas-plink = "^2.2.9"
gtfparse = "^1.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
