[tool.poetry]
name = "dRFEtools"
version = "0.1.0"
description = "A package for preforming dynamic recursive feature elimination with sklearn."
authors = ["Kynon JM Benjamin <kj.benjamin90@gmail.com>"]
license = "GNU General Public License v3 (GPLv3)"
readme = "README.md"
homepage = "https://github.com/paquolalab/dRFEtools.git"
repository = "https://github.com/paquolalab/dRFEtools.git"
keywords = ['recursive feature elimination', 'sklearn', 'feature ranking']
include = [ "LICENSE"]

[tool.poetry.dependencies]
python = ">=3.7.1"
numpy = "1.20.1"
pandas = "1.2.4"
matplotlib = "3.3.4"
plotnine = "0.7.1"
scikit-learn = "^0.24.1"
scipy = "^1.6.0"
statsmodels = "^0.12.2"

[tool.poetry.dev-dependencies]
pandas-plink = "^2.2.9"
gtfparse = "^1.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
